config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
 resources :users, only: [:show, :edit, :update]

  get 'bookings/new', to: 'bookings#new', as: 'new_booking'
  post 'bookings', to: 'bookings#create', as: 'bookings'


  root "home#index"
  get 'calendar', to: 'calendar#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  store :availability, accessors: [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday], coder: JSON
  validates :availability, presence: true
  after_initialize :set_default_availability, if: :new_record?

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0, 20]
      )
    end

    user.update(
      provider: access_token.provider,
      uid: access_token.uid,
      token: access_token.credentials.token,
      refresh_token: access_token.credentials.refresh_token,
      expires_at: Time.at(access_token.credentials.expires_at)
    )
    user
  end

  def update_tokens(auth)
    self.token = auth.credentials.token
    self.refresh_token = auth.credentials.refresh_token
    self.expires_at = Time.at(auth.credentials.expires_at)
    save
  end

  def set_default_availability
    self.availability = {
      "monday" => {"start" => "08:00", "end" => "17:30"},
      "tuesday" => {"start" => "08:00", "end" => "17:30"},
      "wednesday" => {"start" => "08:00", "end" => "17:30"},
      "thursday" => {"start" => "08:00", "end" => "17:30"},
      "friday" => {"start" => "08:00", "end" => "17:30"},
      "saturday" => {"start" => nil, "end" => nil},
      "sunday" => {"start" => nil, "end" => nil}
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_robert_calendar_service, only: [:create]

  def new
    @booker_email = current_user.email
  end

  def create
    date = params[:date]
    time = params[:time]
    duration = params[:duration]

    start_time = DateTime.parse("#{date} #{time}")
    end_time = start_time + params[:duration].to_i.minutes
    summary = params[:summary]
    booker_email = params[:booker_email]
    attendees_emails = params[:attendees].to_s.split(',').map(&:strip)

    start_time = Time.zone.parse("#{date} #{time}").in_time_zone('Europe/Warsaw')
    end_time = start_time + duration.to_i.minutes

    attendees = attendees_emails.map { |email| { email: email } }
    attendees << { email: booker_email }
    attendees << { email: 'robertgradowski00@gmail.com' } unless attendees_emails.include?('robertgradowski00@gmail.com')

    event = @google_calendar_service.create_event(summary, start_time, end_time, attendees)

    if event
      flash[:notice] = "Event successfully created!"
    else
      flash[:alert] = "The selected time slot is not available or there was an error creating the event."
    end

    redirect_to root_path
  end

  private

  def set_robert_calendar_service
    robert_email = 'robertgradowski00@gmail.com'
    @google_calendar_service = GoogleCalendarService.new(current_user, robert_email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    current_user_calendar_service = GoogleCalendarService.new(current_user)
    @user_events = current_user_calendar_service.list_events

    robert_email = 'robertgradowski00@gmail.com'
    robert_calendar_service = GoogleCalendarService.new(current_user, robert_email)
    @robert_events = robert_calendar_service.list_events

    robert = User.find_by(email: robert_email)
    @free_slots = robert_calendar_service.list_free_slots(robert)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  private
  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :availability)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="container">
  <h1>Book an Event</h1>
  <%= form_with url: bookings_path, method: :post, html: { class: 'needs-validation' } do |form| %>
  
    <div class="form-group">
      <%= form.label :summary, "Event Summary", class: "form-label" %>
      <%= form.text_field :summary, class: "form-control", placeholder: "Enter event summary" %>
    </div>
    
    <div class="form-group">
      <%= form.label :date, "Date", class: "form-label" %>
      <%= form.date_field :date, value: Date.today, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= form.label :time, "Time", class: "form-label" %>
      <%= form.time_field :time, value: Time.now.strftime("%H:%M"), class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= form.label :duration, "Duration (minutes)", class: "form-label" %>
      <%= form.number_field :duration, class: "form-control", placeholder: "Enter duration in minutes" %>
    </div>
    
    <div class="form-group mb-1">
      <%= form.label :booker_email, "Your Email", class: "form-label" %>
      <%= form.email_field :booker_email, value: current_user.email, class: "form-control", placeholder: "Enter your email" %>
      <small id="emailHelp" class="form-text text-muted"></small>
    </div>
    
    <div class="form-group">
      <%= form.label :attendees, "Additional Attendees (comma-separated emails)", class: "form-label" %>
      <%= form.text_area :attendees, class: "form-control", placeholder: "Enter attendees' emails" %>
    </div>
    
    
    <div class="form-group mt-3">
      <%= form.submit "Book Event", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/home/index.html.erb
<div class="d-flex container">
  <div class="row justify-content-center align-items-start">
    
    <div class="col-4">
      <div class="card mx-4 my-2">
        <div class="card-header">
          <%= current_user.email %>
        </div>
        <div class="card-body">
          <% if @user_events.any? %>
            <% @user_events.each do |event| %>
              <% start_time = event[:start].to_datetime %>
              <% end_time = event[:end].to_datetime %>
              <div class="card mb-3">
                <div class="card-body">
                  <h5 class="card-title"><%= event[:summary] %></h5>
                  <p class="card-text">
                    <strong>Day:</strong> <%= start_time.to_date.strftime('%A, %B %d, %Y') %><br>
                    <strong>Start Time:</strong> <%= start_time.strftime('%H:%M') %><br>
                    <strong>End Time:</strong> <%= end_time.strftime('%H:%M') %><br>
                    <strong>Calendar:</strong> <%= event[:calendar_name] %>
                  </p>
                </div>
              </div>
            <% end %>
          <% else %>
            <p>No events found.</p>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-4">
      <div class="card mx-4 my-2">
        <div class="card-header">
          Robert's Events
        </div>
        <div class="card-body">
          <% if @robert_events.any? %>
            <% @robert_events.each do |event| %>
              <% start_time = event[:start].to_datetime %>
              <% end_time = event[:end].to_datetime %>
              <div class="card mb-3">
                <div class="card-body">
                  <h5 class="card-title"><%= event[:summary] %></h5>
                  <p class="card-text">
                    <strong>Day:</strong> <%= start_time.to_date.strftime('%A, %B %d, %Y') %><br>
                    <strong>Start Time:</strong> <%= start_time.strftime('%H:%M') %><br>
                    <strong>End Time:</strong> <%= end_time.strftime('%H:%M') %><br>
                    <strong>Calendar:</strong> <%= event[:calendar_name] %>
                  </p>
                </div>
              </div>
            <% end %>
          <% else %>
            <p>No events found.</p>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-4">
      <div class="card mx-4 my-2">
        <div class="card-header">
          Robert's Availability
        </div>
        <div class="card-body">
          <% today = Date.today %>
          <% @free_slots.select { |day_str, _slots| Date.parse(day_str) >= today }.each do |day_str, slots| %>
            <% day = Date.parse(day_str) %>
            <% if slots.any? %>
              <% slots.each do |slot| %>
                <div class="card mb-3">
                  <div class="card-body">
                    <h5 class="card-title"><%= day.strftime('%A, %Y-%m-%d') %></h5>
                    <p class="card-text">
                      <strong>Available Time:</strong> <%= "#{slot.start.strftime('%H:%M')} - #{slot.end.strftime('%H:%M')}" %>
                    </p>
                  </div>
                </div>
              <% end %>
            <% else %>
              <p>No availability found for <%= day.to_s(:long) %>.</p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-12 text-center my-4">
      <% if current_user.email == 'robertgradowski00@gmail.com' %>
        <%= link_to 'Edit Your Availability', edit_user_path(current_user), class: 'btn btn-primary mx-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<br>
<% if notice %>
	<div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger alert-dismissible fade show '>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Scheduler', root_path, class: 'navbar-brand fs-2 mb-1 mx-3' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Book event', new_booking_path, class: 'nav-link active' %>
        </li>
        <% end %>
       <ul class="navbar-nav custom-mr-5">
    <li class="nav-item user-name">
    </li>
    <% if current_user %>
    <li class="nav-item">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "position-absolute top end-0 btn btn-xs btn-outline-danger mx-4", data: { turbo_method: :delete } %>
    </li>
    <% end %>
  </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchedulingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>

  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    


    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container pt-3">
    <%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :email %>
        <%= form.email_field :email, style: 'width: 70%' %>
    </div>

    <h3>Availability</h3>
    <% days_of_week = %w[monday tuesday wednesday thursday friday saturday sunday] %>
    <% days_of_week.each do |day| %>
        <div class="field">
        <%= form.label "#{day}_start", "#{day.capitalize} Start Time" %>
        <%= form.time_field "#{day}[start]", value: @user.availability.dig(day, 'start') %>
        <%= form.label "#{day}_end", "#{day.capitalize} End Time" %>
        <%= form.time_field "#{day}[end]", value: @user.availability.dig(day, 'end') %>
        </div>
    <% end %>

    <div class="actions">
        <%= form.submit %>
    </div>
    <% end %>
</div>

app/views/users/show.html.erb
<h1>User Details</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<h2>Availability</h2>
<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
    <% days_of_week = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] %>
    <% days_of_week.each do |day| %>
      <tr>
        <td><%= day.capitalize %></td>
        <td><%= @user.availability[day]['start'] || 'Not Available' %></td>
        <td><%= @user.availability[day]['end'] || 'Not Available' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>